### ISSUE TITLE
error while installing webpack-dev-server

### ISSUE THREAD

**Issue by allabakash** [ShiniWolf/angular2-symfony3#2]
npm install webpack-dev-server -g
> uglifyjs-webpack-plugin@0.4.6 postinstall /usr/local/lib/node_modules/webpack-dev-server/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> module.js:340
>    throw err;
          ^
> Error: Cannot find module 'sync-exec'
>    at Function.Module._resolveFilename (module.js:338:15)
>    at Function.Module._load (module.js:280:25)
>    at Module.require (module.js:364:17)
>    at require (module.js:380:17)
>    at Object.<anonymous> (/usr/local/lib/node_modules/webpack-dev->server/node_modules/webpack/node_modules/uglifyjs-webpack-plugin/lib/post_install.js:9:14)
>    at Module._compile (module.js:456:26)
>    at Object.Module._extensions..js (module.js:474:10)
>    at Module.load (module.js:356:32)
>    at Function.Module._load (module.js:312:12)
>    at Function.Module.runMain (module.js:497:10)
>npm WARN This failure might be due to the use of legacy binary "node"
>npm WARN For further explanations, please read
>/usr/share/doc/nodejs/README.Debian
> 
>npm ERR! weird error 8
>npm ERR! not ok code 0

**Comment by allabakash** [comment]
after nodejs uninstalled and installed, it got resolved
